name:           HoverGroup
author:         anutron
#current:       0.1
category:       Utilities
tags:           [mouseover, menu, group]
docs:           http://clientcide.com/docs/Layout/HoverGroup
demo:           http://www.clientcide.com/wiki/cnet-libraries/08-layout/0.2-hovergroup